name: Deploy to Amazon ECS

on:
  push:
    branches:
      - "main"

env:
  AWS_REGION: us-east-2                 
  ECR_REPOSITORY: my-first-ecr-repo          
  DEV_ECS_SERVICE: dev-ecs-service               
  DEV_ECS_CLUSTER: dev-cluster
  STAGE_ECS_SERVICE: stage-ecs-service               
  STAGE_ECS_CLUSTER: stage-cluster
  PROD_ECS_SERVICE: prod-ecs-service               
  PROD_ECS_CLUSTER: prod-cluster                  
  ECS_TASK_DEFINITION: .github/workflows/task-definition.json
  CONTAINER_NAME: my-first-task           

permissions:
  id-token: write
  contents: read 
  
jobs:
  build-and-release:
    name: Build, release deploy
    runs-on: ubuntu-latest
    environment: production

    outputs:
      image: ${{ steps.build-image.outputs.image }}
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::893688252992:role/Github
        role-session-name: Github
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        mask-password: "true"

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG_LATEST: latest
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_LATEST -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_LATEST
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
    - name: Deploy to dev
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        service: ${{ env.DEV_ECS_SERVICE }}
        cluster: ${{ env.DEV_ECS_CLUSTER }}
        wait-for-service-stability: true

  deploy-to-stage:
    name: staging
    runs-on: ubuntu-latest
    environment: production
    needs: build-and-release

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::893688252992:role/Github
        role-session-name: Github
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Deploy to Stage
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        service: ${{ env.STAGE_ECS_SERVICE }}
        cluster: ${{ env.STAGE_ECS_CLUSTER }}
        wait-for-service-stability: true